#!/usr/bin/env php
<?php
// -----------------------------------------------------------------------------
// Usage: $ ./phpipam2dhcp <subnet>
//
// Example:
//        $ ./phpipam2dhcp 147.251.90.0/24
//
// Output file:
//        147.251.90.0.conf
// -----------------------------------------------------------------------------

printf("\n");

// subnet is the first argument
if( count($argv) != 2 ){
    printf(">>> ERROR: Subnet not specified!\n\n");
    exit(1);
}

$subnet = $argv[1];
if( $subnet == "" ) {
    printf(">>> ERROR: Subnet not specified!\n\n");
    exit(1);
}

printf("SubNet: %s\n",$subnet);

// access to phpIPAM api
include 'phpipam.conf';

// -----------------------------------------------------------------------------

$subnetid = 0;
$data = [];
$token = "";
$hosts = "";
$subnet_data = "";
$dhcp_classes = [];
$locationsdb = [];

// -----------------------------------------------------------------------------

// stop on any warning
// https://stackoverflow.com/questions/10520390/stop-script-execution-upon-notice-warning

function errHandle($errNo, $errStr, $errFile, $errLine) {
    $msg = "$errStr in $errFile on line $errLine";
    if ($errNo == E_NOTICE || $errNo == E_WARNING) {
        throw new ErrorException($msg, $errNo);
    } else {
        echo $msg;
    }
}

set_error_handler('errHandle');

// -----------------------------------------------------------------------------

function init_session()
{   
    global $url, $username, $passwd, $token;

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url . "user/");
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_USERPWD, "$username:$passwd");
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

    $server_output = curl_exec ($ch);
    
    if( $server_output == FALSE ){
        printf(">>> ERROR: Unable to connect to IPAM: %s\n\n",curl_error($ch));
        curl_close ($ch);
        exit(1);
    }    

    curl_close ($ch);
    
    $json = json_decode($server_output);

    $token = $json->data->token;
    
    //printf("Session token: %s\n",$token);
}

// -----------------------------------------------------------------------------

function get_subnetid()
{   
    global $url, $token, $subnetid, $subnet;

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url . "subnets/cidr/" . $subnet ."/");
    curl_setopt($ch, CURLOPT_HTTPGET, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    
    $headers = [
        "token: $token"
    ];
    
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);    

    $server_output = curl_exec ($ch);
    
    if( $server_output == FALSE ){
        printf(">>> ERROR: Unable to connect to IPAM: %s\n\n",curl_error($ch));
        curl_close ($ch);
        exit(1);
    }    

    curl_close ($ch);
    
    $subnet_data = json_decode($server_output);
    
    if( $subnet_data->success == false ){
        printf(">>> ERROR: Unable to get subnet id for %s\n\n",$subnet);
        var_dump($subnet_data); 
        exit(1);
    }   
        
    $subnetid = $subnet_data->data[0]->id;
}

// -----------------------------------------------------------------------------

function get_subnet()
{   
    global $url, $token, $subnetid, $subnet, $subnet_data;

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url . "subnets/" . $subnetid ."/");
    curl_setopt($ch, CURLOPT_HTTPGET, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    
    $headers = [
        "token: $token"
    ];
    
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);    

    $server_output = curl_exec ($ch);
    
    if( $server_output == FALSE ){
        printf(">>> ERROR: Unable to connect to IPAM: %s\n\n",curl_error($ch));
        curl_close ($ch);
        exit(1);
    }    

    curl_close ($ch);
    
    $subnet_data = json_decode($server_output);
        
    if( $subnet_data->success == false ){
        printf(">>> ERROR: Unable to get hosts for %s\n\n",$subnet);
        var_dump($subnet_data); 
        exit(1);
    } 
}

// -----------------------------------------------------------------------------

function get_vlan()
{   
    global $url, $token, $subnet_data, $subnet, $vlan_data;

    if( $subnet_data->data->vlanId == 0 ){
        printf("\n>>> ERROR: No VLAN defined for %s subnet!\n\n",$subnet);
        exit(1);
    }
    
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url . "vlans/" . $subnet_data->data->vlanId ."/");
    curl_setopt($ch, CURLOPT_HTTPGET, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    
    $headers = [
        "token: $token"
    ];
    
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);    

    $server_output = curl_exec ($ch);
    
    if( $server_output == FALSE ){
        printf(">>> ERROR: Unable to connect to IPAM: %s\n\n",curl_error($ch));
        curl_close ($ch);
        exit(1);
    }    

    curl_close ($ch);
    
    $vlan_data = json_decode($server_output);
        
    if( $vlan_data->success == false ){
        printf(">>> ERROR: Unable to get hosts for %s\n\n",$subnet);
        var_dump($vlan_data); 
        exit(1);
    } 
}

// -----------------------------------------------------------------------------

function get_hosts()
{   
    global $url, $token, $subnetid, $subnet, $hosts;

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url . "subnets/" . $subnetid ."/addresses/");
    curl_setopt($ch, CURLOPT_HTTPGET, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    
    $headers = [
        "token: $token"
    ];
    
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);    

    $server_output = curl_exec ($ch);
    
    if( $server_output == FALSE ){
        printf(">>> ERROR: Unable to connect to IPAM: %s\n\n",curl_error($ch));
        curl_close ($ch);
        exit(1);
    }    

    curl_close ($ch);
    
    $hosts = json_decode($server_output);
        
    if( $hosts->success == false ){
        printf(">>> ERROR: Unable to get hosts for %s\n\n",$subnet);
        var_dump($hosts); 
        exit(1);
    } 
    
}

// -----------------------------------------------------------------------------

function get_location_name($id)
{   
    global $url, $token, $subnet, $locationsdb;

    // is it in cache?
    if( array_key_exists($id, $locationsdb) == true ){
        return($locationsdb[$id]);
    }
    
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url . "tools/locations/" . $id . "/");
    curl_setopt($ch, CURLOPT_HTTPGET, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    
    $headers = [
        "token: $token"
    ];
    
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);    

    $server_output = curl_exec ($ch);
    
    if( $server_output == FALSE ){
        printf(">>> ERROR: Unable to connect to IPAM: %s\n\n",curl_error($ch));
        curl_close ($ch);
        exit(1);
    }    

    curl_close ($ch);
    
    $loc_data = json_decode($server_output);
        
    if( $loc_data->success == false ){
        printf(">>> ERROR: Unable to get hosts for %s\n\n",$subnet);
        var_dump($loc_data); 
        exit(1);
    } 
    
    $name = $loc_data->data->name;
    $locationsdb[$id] = $name;
    return($name);
}



// -----------------------------------------------------------------------------

function print_header()
{          
    printf("\n");          
    printf("ST   Id           IP               HostName                      MAC               DHCP Class   \n");          
    printf("-- ------ ------------------ --------------------------- ------------------- -------------------\n");
}

// -----------------------------------------------------------------------------

function print_data()
{
    global $hosts, $dhcp_classes;

    print_header();
    
    foreach($hosts->data as $item){
        if( ( $item->ip != "" ) && ( $item->hostname != "" ) && ( $item->mac != "" ) && ( $item->custom_DHCP != "NO" ) && ( $item->custom_DHCP != "POOL" ) ){
            printf("%2s % 5d | %-16s | %-25s | %17s | %17s\n",'',$item->id,$item->ip,$item->hostname,$item->mac,$item->custom_DHCP);
            $dhcp_classes[$item->custom_DHCP] = $item->custom_DHCP;
        }
    }
    
    printf("\n");  
    printf("Number of DHCP groups: %d\n",count($dhcp_classes));
}

// -----------------------------------------------------------------------------

function generate_header($fh)
{
    global $url, $subnet_data, $subnet, $vlan_data;
    
    fprintf($fh,"# -----------------------------------------------------------------------------\n");
    fprintf($fh,"# GENERATED BY phpipam2dhcpd - DO NOT EDIT\n");
    fprintf($fh,"# -----------------------------------------------------------------------------\n"); 
    fprintf($fh,"# data source: %s\n",$url);    
    fprintf($fh,"# date       : %s\n",date("Y-m-d H:i:s"));  
    fprintf($fh,"# admin      : %s\n",$subnet_data->data->custom_Admin);
    fprintf($fh,"# tech admin : %s\n",$subnet_data->data->custom_TechAdmin);
    fprintf($fh,"# sec-alerts : %s\n",$subnet_data->data->custom_SecAlerts);
    fprintf($fh,"# -----------------------------------------------------------------------------\n");    
    fprintf($fh,"\n");
    fprintf($fh,"# subnet: %s\n",$subnet);
    fprintf($fh,"# vlan  : %d (%s)\n",$vlan_data->data->number, $vlan_data->data->name);
    fprintf($fh,"# -----------------------------------------------------------------------------\n");      
    fprintf($fh,"\n");
    fprintf($fh,"subnet %s netmask %s {\n",$subnet_data->data->calculation->{'Network'},$subnet_data->data->calculation->{'Subnet netmask'});
    
    fprintf($fh,"   default-lease-time         14400;\n");
    fprintf($fh,"   max-lease-time             28800;\n");
    fprintf($fh,"   deny                       unknown-clients;\n");    
    fprintf($fh,"   deny                       bootp;\n");

    fprintf($fh,"\n");    
    fprintf($fh,"   option routers             %s;\n",$subnet_data->data->calculation->{'Min host IP'});
    fprintf($fh,"   option subnet-mask         %s;\n",$subnet_data->data->calculation->{'Subnet netmask'});    
    fprintf($fh,"   option domain-name-servers 147.251.4.33, 147.251.6.10;\n");
    fprintf($fh,"   option domain-name         %s;\n",$subnet_data->data->custom_Domain);


    // detect DHCP pool
    global $hosts;
   
    $first = true;
    foreach($hosts->data as $item){
        if( ( $item->ip != "" ) && ( $item->mac == "" ) && ( $item->custom_DHCP == "POOL" ) ){
            $pool[] = $item->ip;
            $dp = explode(".",$item->ip);
            $num = 0;
            if( count($dp) == 4 ){
                $num = $dp[3];
            }
            if( $num != 0 ){
                if( $first == true ){
                    $prev = $num;
                } else if( $prev + 1 != $num ){
                    printf(">>> ERROR: Discontinuous pool!\n\n");
                    exit(1); 
                }
            }
        }
    }

    if( count($pool) > 0 ){
    fprintf($fh,"\n");
    fprintf($fh,"   # DHCP pool\n");
    fprintf($fh,"   pool {\n");
    fprintf($fh,"      range %s %s\n",$pool[0],$pool[count($pool)-1]);
    fprintf($fh,"   }\n");
    }
    
    fprintf($fh,"}\n");   
}

// -----------------------------------------------------------------------------

function generate_group_specific($fh,$gname)
{
    
    if( $gname == "PUPPET" ){
        fprintf($fh,"\n");    
        fprintf($fh,"   allow  bootp;\n"); 
        fprintf($fh,"\n");
        fprintf($fh,"   if exists user-class and option user-class = \"iPXE\" {\n");
        fprintf($fh,"       filename \"bootstrap.ipxe\";\n");
        fprintf($fh,"   } else {\n");
        fprintf($fh,"       filename \"undionly.kpxe\";\n");
        fprintf($fh,"   }\n");
        fprintf($fh,"   next-server 147.251.84.53;   # puppet.ncbr.muni.cz\n"); 
        return;
    } 
    
    if( $gname == "PLAIN" ){
        // nothing to be here
        return;
    }
}

// -----------------------------------------------------------------------------

function generate_group($fh,$gname)
{
    global $hosts;

    fprintf($fh,"\n");
    fprintf($fh,"# DHCP group: %s\n",$gname);
    fprintf($fh,"# -----------------------------------------------------------------------------\n");  
    fprintf($fh,"group {\n");
    
    generate_group_specific($fh,$gname);
        
    foreach($hosts->data as $item){
        if( ( $item->ip == "" ) || ( $item->hostname == "" ) || ( $item->mac == "" ) || ( $item->custom_DHCP != $gname ) ) continue;
        fprintf($fh,"\n");        
        fprintf($fh,"# -----\n");
        fprintf($fh,"   host %s {\n",$item->hostname);
        fprintf($fh,"       hardware ethernet %s;\n",$item->mac);
        fprintf($fh,"       fixed-address     %s;\n",$item->ip );
        fprintf($fh,"       option host-name  \"%s\";\n",explode(".",$item->hostname)[0]);
        if( $item->location > 0 ){
        fprintf($fh,"       # Location:       %s\n",get_location_name($item->location));
        }
        if( $item->port != "" ){
        fprintf($fh,"       # Plug/port:      %s\n",$item->port);
        }
        fprintf($fh,"       # Admin:          %s\n",$item->custom_Admin);
        if( $item->custom_User != "" ){
        fprintf($fh,"       # User:           %s\n",$item->custom_User);
        }
        fprintf($fh,"       # Group:          %s\n",$item->custom_Group);
        if( $item->custom_Cluster != "" ){
        fprintf($fh,"       # Cluster:        %s\n",$item->custom_Cluster);
        }

        fprintf($fh,"   }\n");
    }
    
    fprintf($fh,"}\n");
    fprintf($fh,"\n");   
}

// -----------------------------------------------------------------------------

init_session();
get_subnetid();
get_subnet();
get_vlan();
get_hosts();
print_data();

$subnet_items = explode("/", $subnet);
$dhcp_conf = $subnet_items[0] . ".conf";

printf("\n"); 
printf("Generating DHCPD configuration: %s\n",$dhcp_conf);

$fh = fopen($dhcp_conf,"w");
if( $fh == false ){
    printf(">>> ERROR: Unable to open %s for writing!\n\n",$dhcp_conf);
    exit(1);
}

generate_header($fh);
foreach($dhcp_classes as $gname){
    generate_group($fh,$gname);
}

fclose($fh);

printf("Done!\n");
printf("\n");   

?>
